---
- name: Deploy drone ci server
  hosts: drone
  become: true
  vars_prompt:
    - name: ansible_drone_deploy_postgresql
      prompt: "Install postgres database for drone from scratch? (yes/no)"
      default: "no"
    - name: ansible_drone_deploy_server
      prompt: "Install drone server from scratch? (yes/no)"
      default: "no"
    - name: ansible_drone_deploy_agents
      prompt: "Install drone agents from scratch? (yes/no)"
      default: "no"
  vars_files:
    - "vars/credentials.yml"
    - "vars/main.yml"
  roles:
    - role: auxilincom.drone
      drone_rpc_server: "http{{ 's' if server_setup_ssl or server_setup_letsencrypt_ssl else '' }}\
        ://{{ drone_server_host }}"
      drone_server_proto: "http{{'s' if server_setup_ssl or server_setup_letsencrypt_ssl else ''}}"
