version: '3.5'

services:
  drone-server:
    image: drone/drone:1.2.1
    ports:
      - 8000:80
      - 9000:443
    networks:
      - drone
    volumes:
      - ./drone-data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    restart: always
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=localhost:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_HOST=http://localhost:8000
      - DRONE_GITHUB=true
      # Variables below set via drone.env file
      # - DRONE_USER_CREATE=
      # - DRONE_USER_FILTER=
      # - DRONE_GITHUB_CLIENT_ID=
      # - DRONE_GITHUB_CLIENT_SECRET=
      # - DRONE_RPC_SECRET=

  drone-agent:
    image: drone/agent:1.2.1
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_RPC_SERVER=drone-server:8000
      # Variables below set via drone.env file
      # - DRONE_RPC_SECRET=

networks:
  drone:
    name: drone_network
