---
kind: pipeline
name: publish

steps:
- name: publish-api-docker
  image: plugins/docker
  settings:
    dockerfile: ./api/Dockerfile
    context: ./api
    purge: true
    repo: auxilinapp/auxilin-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - latest
    - ${DRONE_BRANCH}
  when:
    event:
    - push

- name: publish-web-docker
  image: plugins/docker
  settings:
    dockerfile: ./web/Dockerfile
    context: ./web
    purge: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: auxilinapp/auxilin-web
    tags:
    - latest
    - ${DRONE_BRANCH}
  when:
    event:
    - push

- name: publish-landing-docker
  image: plugins/docker
  settings:
    dockerfile: ./landing/Dockerfile
    context: ./landing
    purge: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: auxilinapp/auxilin-landing
    tags:
    - latest
    - ${DRONE_BRANCH}
  when:
    event:
    - push

- name: deploy-staging-app
  image: plugins/ansible
  commands:
  - cp ./deploy/app/vars/credentials-template.yml ./deploy/app/vars/credentials.yml
  settings:
    playbook: ./deploy/app/deploy-app.yml
    inventory: ./deploy/app/hosts/staging
    private_key:
      from_secret: ansible_private_key
    extra_vars:
      - docker_tag: latest
      docker_registry_username:
        from_secret: docker_username
      docker_registry_password:
        from_secret: docker_password
      docker_registry_email:
        from_secret: docker_email
      mailgun_api_key:
        from_secret: mailgun_api_key
      mailgun_domain:
        from_secret: mailgun_domain
  when:
    event:
    - push
    status:
    - success

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: tests

steps:
- name: run-test-suite
  image: compose:1.24.1
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up -f ./docker-compose.local-tests.yml
  when:
    event:
    - pull_request

services:
- name: mongo
  image: mongo:4.0.10
- name: redis
  image: redis:5.0.5

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
 branch:
 - master
 event:
 - pull_request
