version: '3.3'
services:
  mongo:
    command: mongod
    image: mongo:4.0.10
    networks:
      - auxilin
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    command: redis
    networks:
      - auxilin
    image: redis:5.0.5
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
  api-tests:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - auxilin
    command: npm test
    depends_on:
      - mongo
      - redis
  web-test:
    build:
      context: "./web"
      dockerfile: Dockerfile
    networks:
      - auxilin
    command: npm test
  landing-test:
    build:
      context: "./landing"
      dockerfile: Dockerfile
    networks:
      - auxilin
    command: npm test

networks:
  auxilin:
    name: auxilin_test_network
