---
- name: Deploy grafana to monitoring server
  hosts: monitoring
  become: true
  gather_facts: False
  vars_files:
    - "vars/main.yml"
    - "vars/credentials.yml"
  tasks:
    - name: Assures directories exists
      file: path="{{ item }}" state=directory owner=root group=root
      with_items:
        - "/etc/grafana/provisioning/dashboards"
        - "/etc/grafana/provisioning/datasources"
        - "/var/lib/grafana"
        - "/var/log/grafana"
        - "/var/lib/grafana/plugins"
        - "/var/lib/grafana/png"
        - "/var/lib/grafana/dashboards"
        - "/var/lib/postgresql/data"
      tags:
        - grafana
        - postgres

    - name: Copy configurations
      template: src="./config/grafana/grafana.ini"
                dest="/etc/grafana/grafana.ini"
                owner=root
                group=root
      tags:
        - grafana

    - name: Copy dashboard config
      template: src="./config/grafana/dashboards.yaml"
                dest="/etc/grafana/provisioning/dashboards/dashboards.yaml"
                owner=root
                group=root
      tags:
        - grafana

    - name: Copy dashboard
      template: src="./config/grafana/{{ item }}.json"
                dest="/var/lib/grafana/dashboards/{{ item }}.json"
                owner=root
                group=root
      with_items:
        - docker
        - linux
        - mongodb
        - redis
      tags:
        - grafana

    - name: Copy influxdb datasorce
      template: src="./config/grafana/datasources.yaml"
                dest="/etc/grafana/provisioning/datasources/datasources.yaml"
                owner=root
                group=root
      tags:
        - grafana

    - name: "Pull PostgreSQL docker image"
      docker_image:
        state: present
        source: pull
        force_source: yes
        name: "postgres:11.3"
        tag: "11.3"
      tags:
        - postgres

    - name: "Launch PostgreSQL container"
      docker_container:
        name: postgres
        image: postgres:11.3
        state: started
        restart_policy: always
        ports:
          - "5432:5432"
        networks:
          - name: "{{ monitoring_network_name }}"
        volumes:
          - /var/lib/postgresql/data:/var/lib/postgresql/data
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
      tags:
        - postgres

    - name: "Pull Grafana docker image"
      docker_image:
        state: present
        source: pull
        force_source: yes
        name: "grafana/grafana:6.2.5"
        tag: "6.2.5"
      tags:
        - grafana

    - name: Make sure psycopg2 is installed
      apt:
        name:
          - python3-psycopg2
          - python-psycopg2
        state: latest
      tags:
        - postgres

    - name: create postgres database
      postgresql_db:
        login_host: "localhost"
        login_password: "{{ postgres_password }}"
        login_user: "{{ postgres_user }}"
        name: "{{ postgres_db_name }}"
        port: "5432"
      tags:
        - postgres

    - name: "Launch Grafana container"
      docker_container:
        name: grafana
        image: grafana/grafana:6.2.5
        state: started
        restart_policy: always
        ports:
          - "3300:3000"
        networks:
          - name: "{{ monitoring_network_name }}"
        volumes:
          - /var/lib/grafana:/var/lib/grafana
          - /etc/grafana:/etc/grafana
          - /var/log/grafana:/var/log/grafana
        env:
          GF_SECURITY_ADMIN_USER: "{{ gf_admin_user }}"
          GF_SECURITY_ADMIN_PASSWORD: "{{ gf_admin_password }}"
      tags:
        - grafana
