---
- name: Deploy Telegraf
  hosts: app
  become: true
  gather_facts: False
  vars_files:
    - "vars/main.yml"
    - "vars/credentials.yml"
  tasks:
    - name: Assures telegraf directories exists
      file: path=/etc/telegraf state=directory
      tags:
        - telegraf
    - name: Copy telegraf configurations
      template: src="config/telegraf/telegraf.conf.j2"
                dest="/etc/telegraf/telegraf.conf"
                owner=root
                group=root
      tags:
        - telegraf

    - name: create application networks
      docker_network:
        name: "{{ app_network_name }}"

    - name: pull telegraf image
      docker_image:
        state: present
        source: pull
        force_source: yes
        name: "telegraf:1.11.1"
        tag: "1.11.1"
      tags:
        - telegraf

    - name: run telegraf via docker
      docker_container:
        name: telegraf
        image: telegraf:1.11.1
        state: started
        restart_policy: always
        force_kill: yes
        ports:
          - "8092:8092/udp"
          - "8125:8125/udp"
          - "8094:8094"
        networks:
          - name: "{{ app_network_name }}"
        volumes:
          - /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /sys:/rootfs/sys:ro
          - /proc:/rootfs/proc:ro
          - /etc:/rootfs/etc:ro
        env:
          HOST_PROC: /rootfs/proc
          HOST_SYS: /rootfs/sys
          HOST_ETC: /rootfs/etc
      tags:
        - telegraf
